var filter = args.Obj("filter");
string ruleSet = args.Str("ruleSet");
var tolerance = args.Obj("tolerance");
var labels = args.Obj("labels");
var detection = args.Obj("detection");
bool includeOutline = args.Bool("includeOutline", true);
int limit = args.Int("limit", 30);
int offset = args.Int("offset", 0);
int maxCandidates = args.Int("maxCandidates", 5000);
return AecTools.ArchDetectRooms(db, ed, tr, units, ct, log, filter, ruleSet, tolerance, labels, detection, includeOutline, limit, offset, maxCandidates);
