using System.Text.Json;
using System.Text.Json.Serialization;
using HPNavis.BIMCoordinator.Rules;
using HPNavis.BIMCoordinator.SearchSets;

namespace HPNavis.BIMCoordinator.Colors;

/// <summary>
///     The colour-set registry: the sets of sheet <c>ColorSearchSet(DSC)</c> in sheet order, each with its RGB (null =
///     <c>&lt;Default&gt;</c>, no override) and the conditions that find its elements. Generated by
///     <c>tools/bim-coordinator/generate-color-sets.py</c> from the workbook + <c>color-set-mapping.json</c> and checked on
///     load against the search-set registry's property table and discipline roles. A <c>pending</c> set has no reliable
///     rule yet: it is neither saved nor painted, only reported.
/// </summary>
public sealed class ColorSetCatalog
{
    public const string ResourceName = "HPNavis.BIMCoordinator.hp-color-sets.json";
    private static readonly Lazy<ColorSetCatalog> Embedded = new(() => Parse(ClashMatrix.ReadResource(ResourceName), BaseSetCatalog.Default));

    public static ColorSetCatalog Default => Embedded.Value;

    [JsonPropertyName("schemaVersion")] public int SchemaVersion { get; set; }
    [JsonPropertyName("source")] public ColorSource Source { get; set; } = new();

    /// <summary>Folder below the registry's top folder that holds every colour set.</summary>
    [JsonPropertyName("folder")] public string Folder { get; set; } = "";

    [JsonPropertyName("sets")] public List<ColorSetEntry> Sets { get; set; } = new();

    /// <summary>The sets that become saved search sets (not pending), in sheet order.</summary>
    public IReadOnlyList<ColorSetEntry> Active => Sets.Where(s => s.Pending is null).OrderBy(s => s.Order).ToList();

    public ColorSetEntry Set(string code) =>
        Sets.FirstOrDefault(s => s.Code == code || s.DisplayName == code) ?? throw new ArgumentException($"no colour set '{code}' (use C01.. or the HP_ name)");

    /// <summary>Search plans of the active sets (all, or the given codes / names) under <c>{top}/{Folder}</c>.</summary>
    public IReadOnlyList<SearchSetPlan> Plans(BaseSetCatalog catalog, IReadOnlyCollection<string>? codes = null)
    {
        var wanted = codes is { Count: > 0 } ? codes.Select(Set).ToList() : Active.ToList();
        var pending = wanted.Where(s => s.Pending is not null).Select(s => s.DisplayName).ToList();
        if (pending.Count > 0) throw new ArgumentException($"colour set(s) {string.Join(", ", pending)} are pending (no reliable rule yet) and cannot be built");
        var path = new[] { catalog.Folder, Folder };
        return wanted.Select(s => SearchSetPlan.ForDefinition(catalog, s.ToDefinition(), SetKind.Color, s.Discipline, path)).ToList();
    }

    public static ColorSetCatalog Parse(string json, BaseSetCatalog catalog)
    {
        var colors = JsonSerializer.Deserialize<ColorSetCatalog>(json) ?? throw new InvalidOperationException("colour registry JSON is empty");
        colors.Validate(catalog);
        return colors;
    }

    private void Validate(BaseSetCatalog catalog)
    {
        void Fail(string message) => throw new InvalidOperationException("colour registry: " + message);

        if (string.IsNullOrWhiteSpace(Folder) || Folder.Contains('/')) Fail("a single folder name is required");
        if (Sets.Count == 0) Fail("no colour set");
        if (Sets.Select(s => s.Code).Distinct().Count() != Sets.Count) Fail("two colour sets share a code");
        if (Sets.Select(s => s.DisplayName).Distinct().Count() != Sets.Count) Fail("two colour sets share a name");
        if (Sets.Select(s => s.Order).Distinct().Count() != Sets.Count) Fail("two colour sets share an order");
        foreach (var set in Sets)
        {
            if (!set.DisplayName.StartsWith("HP_", StringComparison.Ordinal)) Fail($"{set.Code}: '{set.DisplayName}' is not an HP_ name");
            if (set.Rgb is not null && (set.Rgb.Count != 3 || set.Rgb.Any(c => c is < 0 or > 255))) Fail($"{set.DisplayName}: RGB must be three values 0..255");
            if (!catalog.DisciplineRoles.ContainsKey(set.Discipline)) Fail($"{set.DisplayName}: unknown discipline '{set.Discipline}'");
            var foreign = set.Roles.Where(r => !catalog.RolesOf(set.Discipline).Contains(r)).ToList();
            if (foreign.Count > 0) Fail($"{set.DisplayName}: role(s) {string.Join(", ", foreign)} are not {set.Discipline}");
            catalog.ValidateDefinition(set.ToDefinition(), "colour registry");
        }
    }
}

public sealed class ColorSource
{
    [JsonPropertyName("workbook")] public string Workbook { get; set; } = "";
    [JsonPropertyName("sheet")] public string Sheet { get; set; } = "";
    [JsonPropertyName("sha256")] public string Sha256 { get; set; } = "";
    [JsonPropertyName("mapping")] public string Mapping { get; set; } = "";
}

/// <summary>One colour set: the sheet's name, order and RGB, and the conditions that find its elements.</summary>
public sealed class ColorSetEntry
{
    [JsonPropertyName("code")] public string Code { get; set; } = "";
    [JsonPropertyName("displayName")] public string DisplayName { get; set; } = "";
    [JsonPropertyName("name")] public string Name { get; set; } = "";

    /// <summary>Paint order (sheet order): a later set wins where two sets share an element or a nested element.</summary>
    [JsonPropertyName("order")] public int Order { get; set; }

    [JsonPropertyName("system")] public string System { get; set; } = "";
    [JsonPropertyName("purpose")] public string Purpose { get; set; } = "";

    /// <summary>Red, green, blue 0..255; null = the sheet's <c>&lt;Default&gt;</c>: the set exists, nothing is painted.</summary>
    [JsonPropertyName("rgb")] public List<int>? Rgb { get; set; }

    [JsonPropertyName("discipline")] public string Discipline { get; set; } = "";
    [JsonPropertyName("roles")] public List<string> Roles { get; set; } = new();
    [JsonPropertyName("categories")] public List<string> Categories { get; set; } = new();
    [JsonPropertyName("conditions")] public List<ConditionDefinition> Conditions { get; set; } = new();
    [JsonPropertyName("alsoCategories")] public List<string> AlsoCategories { get; set; } = new();

    /// <summary>True when the rule was counted on a real model; false = standard Revit classification, not yet seen.</summary>
    [JsonPropertyName("verified")] public bool Verified { get; set; }

    [JsonPropertyName("evidence")] public string Evidence { get; set; } = "";
    [JsonPropertyName("sourceCell")] public string SourceCell { get; set; } = "";

    /// <summary>Why the set has no rule yet; such a set is reported, never built or painted.</summary>
    [JsonPropertyName("pending")] public string? Pending { get; set; }

    public bool Paints => Rgb is not null && Pending is null;

    public SetDefinition ToDefinition() => new()
    {
        Code = Code,
        Name = Name,
        DisplayNameOverride = DisplayName,
        Categories = Categories,
        Conditions = Conditions,
        AlsoCategories = AlsoCategories,
        Roles = Roles,
        Discipline = Discipline,
        Evidence = Evidence,
    };
}
